name: build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: gradle/wrapper-validation-action@v1
      - run: ./gradlew build

      - uses: actions/upload-artifact@v2
        with:
          name: dependency-tree-diff.jar
          path: build/dependency-tree-diff.jar
          if-no-files-found: error
